### ISSUE TITLE
Influence map resets every ~20s in "track cursor" mode

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KappaTools#626]
Since  #539 was closed, there has been a "jump to" rule option for the static influence map, called "track cursor".

When the caret is over the string declaring the name of an observable, the influence map displays the tabular form for the incoming/outgoing influences on this observable. However, every ~20s, something happens that causes the tabular form to reset to pointing at Origin (i.e. first rule in the model), even though the caret has not moved from the observable's string name.

1) This reset should not let KaSa lose focus on what's the caret on
2) The GUI should support having the caret at more than just the string name of the observable, like the observable's kappa expression, the flanking pipes `|`, the `%obs:`, the whitespace between `%obs:` and the observable's name... I say the entire entry should point to the observable (I'd say entire line, but lines only have meaning where newlines are meaningful, which is not the case since KappaV4 syntax...).

**Comment by feret** [comment]
Indeed, the "tracking cursor" button behavior is rather strange: 
  1) The field "origin" is not updated 
  2) Clicking on the rule seems to work properly (except the field origin), but clicking on the rule label does not make anything.

**Comment by antoinepouille** [comment]
Testing this today

With the current version, I don't see a loss of focus with the caret on the string of the `%obs` name.

What's fun is that
- A `%obs` is selected only when caret is on its name
- A rule is selected when the caret is on its definition, but NOT when on its name

It's pretty not coherent, I'll check this

**Comment by antoinepouille** [comment]
I just merged a revamp of the `track cursor` function :-)

- Now for _both rules and `%obs`_, clicking anywhere on its name or definition selects it
- The interface makes clear what is selected by _showing the rule or obs name in cursor mode_
- Some text is shown to make clearer how to select a rule or obs.
- I don't see any change in selection after a few minutes, I'll say this was fixed in earlier changes. Let me know if you still encounter this, including your OS and if you use electron or a specific browser, and I'll investigate. 

Cheers
